# A simple DLang Continuous Integration file
name: DLang CI

# This action is pushed on any push to a specific branch,
# in this case, the master branch, although you could add others.
on:
  push:
    branches: [ main ]
    
# Every github action needs at least one job.
# We could have multiple jobs, but for now I am only going to include one here.
jobs:
  build_and_test: # This is the name of our job, and you will see it in the 'Actions' tab.
    # We can have our integration tests run on multiple operating systems in 'containers'
    # that are hosted on github. You can create your own as well, or setup a 'container'
    # using a tool like docker if you like. For now, I am going to show you the ubuntu setup.
    # Available environments are here: https://github.com/actions/virtual-environments
    runs-on: ubuntu-20.04
    # These are the steps that will be run every time that we run our script, one will follow
    # the other.
    # You can pretend you would be manually be typing these out in the terminal everytime you did
    # a 'push' before.
    steps:
      - uses: actions/checkout@v2
      - name: Quick check to see where we are and who we are.
        run: pwd && whoami && ls -l
      # For us, we need to setup our linux box which only takes a few moments
      - name: Update packages on linux
        run: sudo apt-get update
      - name: Install sdl2 dependency 
        run: sudo apt-get install -y libsdl2-dev
      - name: Install dlang 
        run: D_VERSION=$(wget -qO - http://downloads.dlang.org/releases/LATEST) && wget -qO dmd.deb http://downloads.dlang.org/releases/2.x/${D_VERSION}/dmd_${D_VERSION}-0_amd64.deb && sudo apt install -y ./dmd.deb && dmd --version && rm -rf dmd.deb 
#      - name: Install SDL2 deb
#        run: wget http://http.us.debian.org/debian/pool/main/libs/libsdl2/libsdl2-dev_2.0.14+dfsg2-3+deb11u1_amd64.deb && sudo apt install -y ./libsdl2-dev_2.0.14+dfsg2-3+deb11u1_amd64.deb && sudo apt-get -f install -y
     
      # See Readme for project; We only run server tests here because running client tests requires
      # the running of server. We tried to run the server in a background process via this file, but it was not having 
      # the expected result
      - name: Setup configuration for install
        run: echo 31 | cat > input.txt && cat input.txt;
      - name: build and run tests of server code
        run: cd ./FinalProject/source/server && dub test 
